### ISSUE TITLE
licence shall be included

### ISSUE THREAD

**Issue by fxia22** [eriche2016/pointnet2.pytorch#1]
Thanks for providing the modelnet40 loader and download script. Though I would like to point out the original license shall be included https://github.com/fxia22/pointnet.pytorch/blob/master/LICENSE. Also consider contributing to that repo by opening PRs. Looking forward to that :D

-Fei

**Comment by eriche2016** [comment]
@fxia22  Thanks. I have included it.

**Comment by fxia22** [comment]
Cool!
